### ISSUE TITLE
Post-deployment refactor

### ISSUE THREAD

**Issue by jjperezaguinaga** [onPoster/app#1]
# Low Hanging Fruits
- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #15

# More detailed features
- [x] #17

# Org
- [x] #10
- [x] #11
- [x] Follow up on comments in [forum](https://ethereum-magicians.org/t/eip-poster-a-ridiculously-simple-general-purpose-social-media-smart-contract/6751/13).

# Possible Roadmap
- [x] #12

**Comment by auryn-macmillan** [comment]
I have been thinking about #12 as well.
Wondering if it's possible to have a separate subgraph for each network and have them all feed into on parent subgraph that aggregates all of the information?

**Comment by jjperezaguinaga** [comment]
Followed up in #19, will call it a day for now while I keep brainstorming in TheGraph + ETHMagicians forum. Also, keen to have this on [HackFS](https://fs.ethglobal.com/), that way I can probably allocate a bit more time and get some extra visibility. WDYT?

**Comment by auryn-macmillan** [comment]
Yeah, I think this would be a fun project for HackFS.

**Comment by jjperezaguinaga** [comment]
Removing #16 for now, closing this finally.
