### ISSUE TITLE
Add fathom analytics (privacy friendly tracker)

### ISSUE THREAD

**Issue by jjperezaguinaga** [onPoster/app#16]

**Comment by auryn-macmillan** [comment]
Ideally I'd like the app to be static and hosted on IPFS, not sure how this would impact using something like fathom.
Fathom seems ok from a privacy perspective, I'd want to make the dashboard 100% open though.

**Comment by jjperezaguinaga** [comment]
[Fleek](https://fleek.co/) (what I'm currently using) deploys to [IPFS](https://ipfs.fleek.co/ipfs/QmcQHeQxEust1hmt1XKH3bsZ9LWQTrbvRjycwrVpPm4Y89/) automatically. Right now I need to tweak the app so it actually works a static browsable IPFs page (see #15). 

I'm happy to upfront Fanthom analytics since they are privacy-friendly and currently in use in other projects. We can remove it or discuss upgrading if we ever get anything close to their limit.
![image](https://user-images.githubusercontent.com/1128312/127765325-3e0ce2e0-d36f-4333-8ef2-976d969dffb9.png)


You can make them public, which would indeed be the idea.
![image](https://user-images.githubusercontent.com/1128312/127765309-85704983-e56f-41aa-b49e-cbcc38347a2d.png)

**Comment by jjperezaguinaga** [comment]
I'll be a bit more strict moving onwards on adding centralized points of failure, so we will pass on this for now. We might need it later, but right now there's not enough adoption to justify having a tracker, albeit a private one. Closing.
