### ISSUE TITLE
Subgraph deployment

### ISSUE THREAD

**Issue by jjperezaguinaga** [onPoster/app#19]
- [x] #20
- [x] #21
- [x] #22
- [x] #23

There might be other subgraphs available (e.g. Celo), but for now, I believe these are the EVM compatible ones worth having deployed.

**Comment by auryn-macmillan** [comment]
It probably goes without saying, but mainnet Ethereum is a must.

Also any rollups as they go live; arbitrum, optimism, and zk-sync.

**Comment by jjperezaguinaga** [comment]
![image](https://user-images.githubusercontent.com/1128312/127970600-2f765aa0-c7b9-480c-9fd2-e2adb69afa9c.png)

**Comment by jjperezaguinaga** [comment]
> It probably goes without saying, but mainnet Ethereum is a must.
> 
> Also any rollups as they go live; arbitrum, optimism, and zk-sync.

To be completed in https://github.com/onPoster/subgraph/issues/10, closing this one for now.
